language: node_js
node_js:
- '0.10'
sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py

after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
after_failure:
  - python travis_after_all.py
  - export $(cat .to_export_back)
before_deploy:
  - rm -f travis_after_all.py .to_export_back
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS

env:
  global:
    # saucelabs
    - secure: Mnb1vyeonjxbYNRgDARMuznC1iI4Rb2tfEM1OR2nJQE3Ln+1X/B60nXNOA0O2WdRQuZQHMPGQpAhxojd+YTLbalU+nmXgEVn7YJWH7yc3vj2fh6IWWooUtukK2rDfUzRInjVP09XyZlgTjNd7nYZLImC9JH6steypTFq2FKF/Yg=
    - secure: Pv2nyUD133hzft9nfCzJFYwYIusn9QPM3LQcuuunUDfcmV0u5Tb+4cAjS4cc55bYnL8BZYayhJpKUgJUowEHDsmJmpsfFkUxAm9DLztcmxYQ6tvChh/QOkvVgS8+TFdHGSwaKeEWiFQJjRSchl6cITDJCNiF9qiYAqOwgbBVz4U=
    # github token
    - secure: FGMPuZuj/oY1nCnumynswd5AoWUJcrVsE1u6iuN0ICrGJ7s9phl3bGUuxZVi1xYPcFQ+8MyE+13o6u65x9i20SJvFREPNXro5qg8JCoLntYZfHqho8s/jemsVgZyqSSH7xr/pDz6rJC2CzA385rhu/cb1F5wcosiA80ArX1pKuU=
  matrix:
    - TEST_CLIENT=node
    - TEST_CLIENT=selenium:firefox
    - TEST_CLIENT="saucelabs:internet explorer:10:Windows 8"


deploy:
  provider: npm
  email: gregor@martynus.net
  # Very important. Don't forget this one.
  skip_cleanup: true
  # Travis currently only supports the old auth key format.
  # Do `echo -n "username:password" | base64` to get it.
  # Encrypt this. See notes.
  api_key:
  - secure: BKo+8skheMJEnLuB++jsb2bd5yO1kb/X1muRh0nMOVohnz30+pD28MlB2U6qEAUUr7c3wwZBdvz1f0vCjaU/mlRt1/Nz/4pw82PnAYJiohGljDX6nMvov1CPpwvF40QcjPMkOsp9DhnDsvO0OLil/f1lDuEhiVFBBuByQLaiOnQ=
  on:
    branch: master
    repo: gr2m/humble-localstorage

